name: MaraDB Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Lua
        uses: leafo/gh-actions-lua@v9
        with:
          luaVersion: "5.4"

      - name: Run tests
        run: |
          # Create a wrapper script to capture the test result
          cat > run_tests.lua << 'EOF'
          local success = dofile("maradb.tests.lua")
          if success == true then
            os.exit(0)  -- Tests passed
          else
            os.exit(1)  -- Tests failed
          end
          EOF
          
          # Run the tests
          lua run_tests.lua